### ISSUE TITLE
Filter/sort admins lists by column

### ISSUE THREAD

**Issue by kwestein** [OttawaU-RSSP/OttawaU-RSSP#62]
From Emily: "Is it possible to make our lists of lawyers, sponsor groups, and students sortable by each column? This will let our various local admins sort by city and will let us quickly see where something is actionable."

@rbaylis91 I can do the implementation of this but would love if you could help me figure out the design/best way to do this.

**Comment by Rusty-UX** [comment]
@kwestein I think something like this would work well
http://tablesorter.com/docs/#Demo

I can style once it's in place
